using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Philadelphia Eagles offensive linemen (C, G, T).
    /// </summary>
    public static class EaglesOLSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Centers
                new Player
                {
                    TeamId = teamId,
                    Number = 62,
                    LastName = "Kelce",
                    FirstName = "Jason",
                    Position = Positions.C,
                    Height = "6-3",
                    Weight = 295,
                    Age = 28,
                    Exp = 6,
                    College = "Cincinnati",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 84
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 68,
                    LastName = "Andrews",
                    FirstName = "Josh",
                    Position = Positions.C,
                    Height = "6-2",
                    Weight = 311,
                    Age = 25,
                    Exp = 2,
                    College = "Oregon State",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 86
                },

                // Guards
                new Player
                {
                    TeamId = teamId,
                    Number = 79,
                    LastName = "Brooks",
                    FirstName = "Brandon",
                    Position = Positions.G,
                    Height = "6-5",
                    Weight = 335,
                    Age = 27,
                    Exp = 5,
                    College = "Miami (Ohio)",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 87
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 73,
                    LastName = "Seumalo",
                    FirstName = "Isaac",
                    Position = Positions.G,
                    Height = "6-4",
                    Weight = 303,
                    Age = 22,
                    Exp = 0,
                    College = "Oregon State",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 82
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 76,
                    LastName = "Barbre",
                    FirstName = "Allen",
                    Position = Positions.G,
                    Height = "6-4",
                    Weight = 310,
                    Age = 32,
                    Exp = 9,
                    College = "Missouri Southern State",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 94
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 64,
                    LastName = "Tobin",
                    FirstName = "Matt",
                    Position = Positions.G,
                    Height = "6-6",
                    Weight = 290,
                    Age = 26,
                    Exp = 4,
                    College = "Iowa",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 79
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 69,
                    LastName = "Gordon",
                    FirstName = "Dillon",
                    Position = Positions.G,
                    Height = "6-4",
                    Weight = 322,
                    Age = 23,
                    Exp = 0,
                    College = "LSU",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 81
                },

                // Tackles
                new Player
                {
                    TeamId = teamId,
                    Number = 71,
                    LastName = "Peters",
                    FirstName = "Jason",
                    Position = Positions.T,
                    Height = "6-4",
                    Weight = 328,
                    Age = 34,
                    Exp = 13,
                    College = "Arkansas",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 90
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 65,
                    LastName = "Johnson",
                    FirstName = "Lane",
                    Position = Positions.T,
                    Height = "6-6",
                    Weight = 317,
                    Age = 26,
                    Exp = 4,
                    College = "Oklahoma",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 88
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 72,
                    LastName = "Vaitai",
                    FirstName = "Halapoulivaati",
                    Position = Positions.T,
                    Height = "6-6",
                    Weight = 320,
                    Age = 22,
                    Exp = 0,
                    College = "TCU",
                    Speed = 61,
                    Strength = 91,
                    Agility = 66,
                    Awareness = 81,
                    Fragility = 16,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 91,
                    Tackling = 61,
                    Coverage = 31,
                    Kicking = 11,
                    Potential = 81,
                    Progression = 76,
                    Health = 91,
                    Discipline = 82
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} OL (C/G/T)");
        }
    }
}
