using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Philadelphia Eagles wide receivers.
    /// </summary>
    public static class EaglesWRSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                new Player
                {
                    TeamId = teamId,
                    Number = 81,
                    LastName = "Matthews",
                    FirstName = "Jordan",
                    Position = Positions.WR,
                    Height = "6-3",
                    Weight = 212,
                    Age = 24,
                    Exp = 3,
                    College = "Vanderbilt",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 75
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 17,
                    LastName = "Agholor",
                    FirstName = "Nelson",
                    Position = Positions.WR,
                    Height = "6-0",
                    Weight = 198,
                    Age = 23,
                    Exp = 2,
                    College = "USC",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 76
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 82,
                    LastName = "Smith",
                    FirstName = "Torrey",
                    Position = Positions.WR,
                    Height = "6-0",
                    Weight = 204,
                    Age = 27,
                    Exp = 6,
                    College = "Maryland",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 79
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 16,
                    LastName = "Treggs",
                    FirstName = "Bryce",
                    Position = Positions.WR,
                    Height = "6-0",
                    Weight = 185,
                    Age = 22,
                    Exp = 0,
                    College = "California",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 74
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 19,
                    LastName = "Turner",
                    FirstName = "Paul",
                    Position = Positions.WR,
                    Height = "5-9",
                    Weight = 190,
                    Age = 25,
                    Exp = 0,
                    College = "Louisiana Tech",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 82
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 18,
                    LastName = "Green-Beckham",
                    FirstName = "Dorial",
                    Position = Positions.WR,
                    Height = "6-5",
                    Weight = 237,
                    Age = 23,
                    Exp = 2,
                    College = "Oklahoma",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 74
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 13,
                    LastName = "Huff",
                    FirstName = "Josh",
                    Position = Positions.WR,
                    Height = "5-11",
                    Weight = 206,
                    Age = 24,
                    Exp = 3,
                    College = "Oregon",
                    Speed = 94,
                    Strength = 72,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 16,
                    Morale = 91,
                    Passing = 16,
                    Catching = 94,
                    Rushing = 62,
                    Blocking = 42,
                    Tackling = 32,
                    Coverage = 32,
                    Kicking = 12,
                    Potential = 91,
                    Progression = 86,
                    Health = 96,
                    Discipline = 81
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} WRs");
        }
    }
}
