using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Philadelphia Eagles defensive backs (CB, S)
    /// </summary>
    public static class EaglesDBSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Cornerbacks
                new Player
                {
                    TeamId = teamId,
                    Number = 22,
                    LastName = "Carroll",
                    FirstName = "Nolan",
                    Position = Positions.CB,
                    Height = "6-1",
                    Weight = 205,
                    Age = 29,
                    Exp = 7,
                    College = "Maryland",
                    Speed = 93,
                    Strength = 66,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 19,
                    Morale = 91,
                    Passing = 16,
                    Catching = 71,
                    Rushing = 31,
                    Blocking = 26,
                    Tackling = 81,
                    Coverage = 96,
                    Kicking = 11,
                    Potential = 89,
                    Progression = 81,
                    Health = 96,
                    Discipline = 70
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 33,
                    LastName = "Brooks",
                    FirstName = "Ron",
                    Position = Positions.CB,
                    Height = "5-10",
                    Weight = 190,
                    Age = 27,
                    Exp = 5,
                    College = "LSU",
                    Speed = 93,
                    Strength = 66,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 19,
                    Morale = 91,
                    Passing = 16,
                    Catching = 71,
                    Rushing = 31,
                    Blocking = 26,
                    Tackling = 81,
                    Coverage = 96,
                    Kicking = 11,
                    Potential = 89,
                    Progression = 81,
                    Health = 96,
                    Discipline = 65
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 21,
                    LastName = "McKelvin",
                    FirstName = "Leodis",
                    Position = Positions.CB,
                    Height = "5-10",
                    Weight = 185,
                    Age = 31,
                    Exp = 9,
                    College = "Troy",
                    Speed = 93,
                    Strength = 66,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 19,
                    Morale = 91,
                    Passing = 16,
                    Catching = 71,
                    Rushing = 31,
                    Blocking = 26,
                    Tackling = 81,
                    Coverage = 96,
                    Kicking = 11,
                    Potential = 89,
                    Progression = 81,
                    Health = 96,
                    Discipline = 72
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 31,
                    LastName = "Mills",
                    FirstName = "Jalen",
                    Position = Positions.CB,
                    Height = "6-0",
                    Weight = 196,
                    Age = 22,
                    Exp = 0,
                    College = "LSU",
                    Speed = 93,
                    Strength = 66,
                    Agility = 96,
                    Awareness = 86,
                    Fragility = 19,
                    Morale = 91,
                    Passing = 16,
                    Catching = 71,
                    Rushing = 31,
                    Blocking = 26,
                    Tackling = 81,
                    Coverage = 96,
                    Kicking = 11,
                    Potential = 89,
                    Progression = 81,
                    Health = 96,
                    Discipline = 62
                },

                // Safeties
                new Player
                {
                    TeamId = teamId,
                    Number = 27,
                    LastName = "Jenkins",
                    FirstName = "Malcolm",
                    Position = Positions.S,
                    Height = "6-0",
                    Weight = 204,
                    Age = 28,
                    Exp = 8,
                    College = "Ohio State",
                    Speed = 86,
                    Strength = 71,
                    Agility = 89,
                    Awareness = 81,
                    Fragility = 21,
                    Morale = 86,
                    Passing = 16,
                    Catching = 61,
                    Rushing = 26,
                    Blocking = 31,
                    Tackling = 86,
                    Coverage = 91,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 76,
                    Health = 93,
                    Discipline = 71
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 23,
                    LastName = "McLeod",
                    FirstName = "Rodney",
                    Position = Positions.S,
                    Height = "5-10",
                    Weight = 195,
                    Age = 26,
                    Exp = 5,
                    College = "Virginia",
                    Speed = 86,
                    Strength = 71,
                    Agility = 89,
                    Awareness = 81,
                    Fragility = 21,
                    Morale = 86,
                    Passing = 16,
                    Catching = 61,
                    Rushing = 26,
                    Blocking = 31,
                    Tackling = 86,
                    Coverage = 91,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 76,
                    Health = 93,
                    Discipline = 73
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 29,
                    LastName = "Brooks",
                    FirstName = "Terrence",
                    Position = Positions.S,
                    Height = "5-11",
                    Weight = 200,
                    Age = 24,
                    Exp = 3,
                    College = "Florida State",
                    Speed = 86,
                    Strength = 71,
                    Agility = 89,
                    Awareness = 81,
                    Fragility = 21,
                    Morale = 86,
                    Passing = 16,
                    Catching = 61,
                    Rushing = 26,
                    Blocking = 31,
                    Tackling = 86,
                    Coverage = 91,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 76,
                    Health = 93,
                    Discipline = 65
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 42,
                    LastName = "Maragos",
                    FirstName = "Chris",
                    Position = Positions.S,
                    Height = "5-10",
                    Weight = 200,
                    Age = 29,
                    Exp = 7,
                    College = "Wisconsin",
                    Speed = 86,
                    Strength = 71,
                    Agility = 89,
                    Awareness = 81,
                    Fragility = 21,
                    Morale = 86,
                    Passing = 16,
                    Catching = 61,
                    Rushing = 26,
                    Blocking = 31,
                    Tackling = 86,
                    Coverage = 91,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 76,
                    Health = 93,
                    Discipline = 73
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 37,
                    LastName = "Watkins",
                    FirstName = "Jaylen",
                    Position = Positions.S,
                    Height = "6-0",
                    Weight = 194,
                    Age = 24,
                    Exp = 3,
                    College = "Florida",
                    Speed = 86,
                    Strength = 71,
                    Agility = 89,
                    Awareness = 81,
                    Fragility = 21,
                    Morale = 86,
                    Passing = 16,
                    Catching = 61,
                    Rushing = 26,
                    Blocking = 31,
                    Tackling = 86,
                    Coverage = 91,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 76,
                    Health = 93,
                    Discipline = 67
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} DBs (CB/S)");
        }
    }
}
