using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Philadelphia Eagles defensive linemen (DE, DT)
    /// </summary>
    public static class EaglesDLSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Defensive Ends
                new Player
                {
                    TeamId = teamId,
                    Number = 55,
                    LastName = "Graham",
                    FirstName = "Brandon",
                    Position = Positions.DE,
                    Height = "6-2",
                    Weight = 265,
                    Age = 28,
                    Exp = 7,
                    College = "Michigan",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 82
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 98,
                    LastName = "Barwin",
                    FirstName = "Connor",
                    Position = Positions.DE,
                    Height = "6-4",
                    Weight = 264,
                    Age = 29,
                    Exp = 8,
                    College = "Cincinnati",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 77
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 75,
                    LastName = "Curry",
                    FirstName = "Vinny",
                    Position = Positions.DE,
                    Height = "6-3",
                    Weight = 279,
                    Age = 28,
                    Exp = 5,
                    College = "Marshall",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 71
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 90,
                    LastName = "Smith",
                    FirstName = "Marcus",
                    Position = Positions.DE,
                    Height = "6-3",
                    Weight = 251,
                    Age = 24,
                    Exp = 3,
                    College = "Louisville",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 78
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 51,
                    LastName = "Means",
                    FirstName = "Steven",
                    Position = Positions.DE,
                    Height = "6-3",
                    Weight = 263,
                    Age = 26,
                    Exp = 2,
                    College = "Buffalo",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 67
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 56,
                    LastName = "Braman",
                    FirstName = "Bryan",
                    Position = Positions.DE,
                    Height = "6-5",
                    Weight = 241,
                    Age = 29,
                    Exp = 6,
                    College = "West Texas A&M",
                    Speed = 71,
                    Strength = 91,
                    Agility = 76,
                    Awareness = 81,
                    Fragility = 19,
                    Morale = 86,
                    Passing = 11,
                    Catching = 21,
                    Rushing = 21,
                    Blocking = 71,
                    Tackling = 91,
                    Coverage = 41,
                    Kicking = 11,
                    Potential = 86,
                    Progression = 81,
                    Health = 93,
                    Discipline = 77
                },

                // Defensive Tackles
                new Player
                {
                    TeamId = teamId,
                    Number = 91,
                    LastName = "Cox",
                    FirstName = "Fletcher",
                    Position = Positions.DT,
                    Height = "6-4",
                    Weight = 310,
                    Age = 25,
                    Exp = 5,
                    College = "Mississippi State",
                    Speed = 66,
                    Strength = 96,
                    Agility = 72,
                    Awareness = 81,
                    Fragility = 23,
                    Morale = 89,
                    Passing = 11,
                    Catching = 22,
                    Rushing = 22,
                    Blocking = 72,
                    Tackling = 96,
                    Coverage = 42,
                    Kicking = 12,
                    Potential = 81,
                    Progression = 71,
                    Health = 91,
                    Discipline = 71
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 96,
                    LastName = "Logan",
                    FirstName = "Bennie",
                    Position = Positions.DT,
                    Height = "6-2",
                    Weight = 315,
                    Age = 26,
                    Exp = 4,
                    College = "LSU",
                    Speed = 66,
                    Strength = 96,
                    Agility = 72,
                    Awareness = 81,
                    Fragility = 23,
                    Morale = 89,
                    Passing = 11,
                    Catching = 22,
                    Rushing = 22,
                    Blocking = 72,
                    Tackling = 96,
                    Coverage = 42,
                    Kicking = 12,
                    Potential = 81,
                    Progression = 71,
                    Health = 91,
                    Discipline = 79
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 94,
                    LastName = "Allen",
                    FirstName = "Beau",
                    Position = Positions.DT,
                    Height = "6-3",
                    Weight = 327,
                    Age = 24,
                    Exp = 3,
                    College = "Wisconsin",
                    Speed = 66,
                    Strength = 96,
                    Agility = 72,
                    Awareness = 81,
                    Fragility = 23,
                    Morale = 89,
                    Passing = 11,
                    Catching = 22,
                    Rushing = 22,
                    Blocking = 72,
                    Tackling = 96,
                    Coverage = 42,
                    Kicking = 12,
                    Potential = 81,
                    Progression = 71,
                    Health = 91,
                    Discipline = 72
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} DL (DE/DT)");
        }
    }
}
