using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Atlanta Falcons offensive linemen (C, G, T).
    /// </summary>
    public static class FalconsOLSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Center
                new Player
                {
                    TeamId = teamId,
                    Number = 51,
                    LastName = "Mack",
                    FirstName = "Alex",
                    Position = Positions.C,
                    Height = "6-4",
                    Weight = 311,
                    Age = 30,
                    Exp = 8,
                    College = "California",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 83
                },

                // Guards
                new Player
                {
                    TeamId = teamId,
                    Number = 63,
                    LastName = "Garland",
                    FirstName = "Ben",
                    Position = Positions.G,
                    Height = "6-5",
                    Weight = 308,
                    Age = 28,
                    Exp = 3,
                    College = "Air Force",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 87
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 65,
                    LastName = "Chester",
                    FirstName = "Chris",
                    Position = Positions.G,
                    Height = "6-3",
                    Weight = 303,
                    Age = 33,
                    Exp = 11,
                    College = "Oklahoma",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 95
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 67,
                    LastName = "Levitre",
                    FirstName = "Andy",
                    Position = Positions.G,
                    Height = "6-2",
                    Weight = 303,
                    Age = 30,
                    Exp = 8,
                    College = "Oregon State",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 87
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 68,
                    LastName = "Person",
                    FirstName = "Mike",
                    Position = Positions.G,
                    Height = "6-4",
                    Weight = 300,
                    Age = 28,
                    Exp = 3,
                    College = "Montana State",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 85
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 71,
                    LastName = "Schweitzer",
                    FirstName = "Wes",
                    Position = Positions.G,
                    Height = "6-5",
                    Weight = 314,
                    Age = 23,
                    Exp = 0,
                    College = "San Jose State",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 83
                },

                // Tackles
                new Player
                {
                    TeamId = teamId,
                    Number = 70,
                    LastName = "Matthews",
                    FirstName = "Jake",
                    Position = Positions.T,
                    Height = "6-5",
                    Weight = 305,
                    Age = 24,
                    Exp = 3,
                    College = "Texas A&M",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 80
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 73,
                    LastName = "Schraeder",
                    FirstName = "Ryan",
                    Position = Positions.T,
                    Height = "6-7",
                    Weight = 300,
                    Age = 28,
                    Exp = 4,
                    College = "Valdosta State",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 87
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 76,
                    LastName = "Compton",
                    FirstName = "Tom",
                    Position = Positions.T,
                    Height = "6-5",
                    Weight = 308,
                    Age = 27,
                    Exp = 4,
                    College = "South Dakota",
                    Speed = 60,
                    Strength = 90,
                    Agility = 65,
                    Awareness = 80,
                    Fragility = 15,
                    Morale = 85,
                    Passing = 10,
                    Catching = 20,
                    Rushing = 20,
                    Blocking = 90,
                    Tackling = 60,
                    Coverage = 30,
                    Kicking = 10,
                    Potential = 80,
                    Progression = 75,
                    Health = 90,
                    Discipline = 80
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} OL (C/G/T)");
        }
    }
}
