using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Atlanta Falcons linebackers (LB, OLB).
    /// </summary>
    public static class FalconsLBSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Outside Linebackers
                new Player
                {
                    TeamId = teamId,
                    Number = 44,
                    LastName = "Beasley",
                    FirstName = "Vic",
                    Position = Positions.OLB,
                    Height = "6-3",
                    Weight = 246,
                    Age = 24,
                    Exp = 2,
                    College = "Clemson",
                    Speed = 88,
                    Strength = 85,
                    Agility = 90,
                    Awareness = 80,
                    Fragility = 19,
                    Morale = 87,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 90,
                    Coverage = 85,
                    Kicking = 10,
                    Potential = 90,
                    Progression = 85,
                    Health = 95,
                    Discipline = 75
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 50,
                    LastName = "Reed",
                    FirstName = "Brooks",
                    Position = Positions.OLB,
                    Height = "6-3",
                    Weight = 254,
                    Age = 29,
                    Exp = 6,
                    College = "Arizona",
                    Speed = 88,
                    Strength = 85,
                    Agility = 90,
                    Awareness = 80,
                    Fragility = 19,
                    Morale = 87,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 90,
                    Coverage = 85,
                    Kicking = 10,
                    Potential = 90,
                    Progression = 85,
                    Health = 95,
                    Discipline = 72
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 54,
                    LastName = "Schofield",
                    FirstName = "O'Brien",
                    Position = Positions.OLB,
                    Height = "6-3",
                    Weight = 242,
                    Age = 29,
                    Exp = 6,
                    College = "Wisconsin",
                    Speed = 88,
                    Strength = 85,
                    Agility = 90,
                    Awareness = 80,
                    Fragility = 19,
                    Morale = 87,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 90,
                    Coverage = 85,
                    Kicking = 10,
                    Potential = 90,
                    Progression = 85,
                    Health = 95,
                    Discipline = 71
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 59,
                    LastName = "Campbell",
                    FirstName = "De'Vondre",
                    Position = Positions.OLB,
                    Height = "6-4",
                    Weight = 232,
                    Age = 23,
                    Exp = 0,
                    College = "Minnesota",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 72
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 91,
                    LastName = "Upshaw",
                    FirstName = "Courtney",
                    Position = Positions.OLB,
                    Height = "6-2",
                    Weight = 272,
                    Age = 26,
                    Exp = 5,
                    College = "Alabama",
                    Speed = 88,
                    Strength = 85,
                    Agility = 90,
                    Awareness = 80,
                    Fragility = 19,
                    Morale = 87,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 90,
                    Coverage = 85,
                    Kicking = 10,
                    Potential = 90,
                    Progression = 85,
                    Health = 95,
                    Discipline = 80
                },

                // Inside Linebackers
                new Player
                {
                    TeamId = teamId,
                    Number = 41,
                    LastName = "Wheeler",
                    FirstName = "Philip",
                    Position = Positions.LB,
                    Height = "6-2",
                    Weight = 245,
                    Age = 31,
                    Exp = 9,
                    College = "Georgia Tech",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 74
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 45,
                    LastName = "Jones",
                    FirstName = "Deion",
                    Position = Positions.LB,
                    Height = "6-1",
                    Weight = 222,
                    Age = 21,
                    Exp = 0,
                    College = "LSU",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 69
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 53,
                    LastName = "Reynolds",
                    FirstName = "LaRoy",
                    Position = Positions.LB,
                    Height = "6-1",
                    Weight = 240,
                    Age = 25,
                    Exp = 4,
                    College = "Virginia",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 76
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 55,
                    LastName = "Worrilow",
                    FirstName = "Paul",
                    Position = Positions.LB,
                    Height = "6-0",
                    Weight = 230,
                    Age = 26,
                    Exp = 4,
                    College = "Delaware",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 72
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 56,
                    LastName = "Weatherspoon",
                    FirstName = "Sean",
                    Position = Positions.LB,
                    Height = "6-2",
                    Weight = 244,
                    Age = 28,
                    Exp = 6,
                    College = "Missouri",
                    Speed = 85,
                    Strength = 80,
                    Agility = 88,
                    Awareness = 78,
                    Fragility = 18,
                    Morale = 85,
                    Passing = 15,
                    Catching = 50,
                    Rushing = 35,
                    Blocking = 55,
                    Tackling = 88,
                    Coverage = 80,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 93,
                    Discipline = 78
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} LBs (LB/OLB)");
        }
    }
}
