using DomainObjects;
using static DomainObjects.StatTypes;

namespace DataAccessLayer.SeedData
{
    /// <summary>
    /// Seeds Atlanta Falcons defensive backs (CB, S, FS).
    /// </summary>
    public static class FalconsDBSeeder
    {
        public static async Task SeedAsync(GridironDbContext db, int teamId)
        {
            var players = new[]
            {
                // Cornerbacks
                new Player
                {
                    TeamId = teamId,
                    Number = 21,
                    LastName = "Trufant",
                    FirstName = "Desmond",
                    Position = Positions.CB,
                    Height = "6-0",
                    Weight = 190,
                    Age = 26,
                    Exp = 4,
                    College = "Washington",
                    Speed = 92,
                    Strength = 65,
                    Agility = 95,
                    Awareness = 85,
                    Fragility = 18,
                    Morale = 90,
                    Passing = 15,
                    Catching = 70,
                    Rushing = 30,
                    Blocking = 25,
                    Tackling = 80,
                    Coverage = 95,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 95,
                    Discipline = 69
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 23,
                    LastName = "Alford",
                    FirstName = "Robert",
                    Position = Positions.CB,
                    Height = "5-10",
                    Weight = 186,
                    Age = 27,
                    Exp = 4,
                    College = "Southeastern Louisiana",
                    Speed = 92,
                    Strength = 65,
                    Agility = 95,
                    Awareness = 85,
                    Fragility = 18,
                    Morale = 90,
                    Passing = 15,
                    Catching = 70,
                    Rushing = 30,
                    Blocking = 25,
                    Tackling = 80,
                    Coverage = 95,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 95,
                    Discipline = 68
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 29,
                    LastName = "Goodwin",
                    FirstName = "C.J.",
                    Position = Positions.CB,
                    Height = "6-3",
                    Weight = 190,
                    Age = 26,
                    Exp = 1,
                    College = "California (PA)",
                    Speed = 92,
                    Strength = 65,
                    Agility = 95,
                    Awareness = 85,
                    Fragility = 18,
                    Morale = 90,
                    Passing = 15,
                    Catching = 70,
                    Rushing = 30,
                    Blocking = 25,
                    Tackling = 80,
                    Coverage = 95,
                    Kicking = 10,
                    Potential = 88,
                    Progression = 80,
                    Health = 95,
                    Discipline = 67
                },

                // Safeties
                new Player
                {
                    TeamId = teamId,
                    Number = 22,
                    LastName = "Neal",
                    FirstName = "Keanu",
                    Position = Positions.S,
                    Height = "6-0",
                    Weight = 211,
                    Age = 21,
                    Exp = 0,
                    College = "Florida",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 66
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 27,
                    LastName = "Therezie",
                    FirstName = "Robenson",
                    Position = Positions.S,
                    Height = "5-9",
                    Weight = 212,
                    Age = 25,
                    Exp = 2,
                    College = "Auburn",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 69
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 34,
                    LastName = "Poole",
                    FirstName = "Brian",
                    Position = Positions.S,
                    Height = "5-10",
                    Weight = 211,
                    Age = 23,
                    Exp = 0,
                    College = "Florida",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 68
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 36,
                    LastName = "Ishmael",
                    FirstName = "Kemal",
                    Position = Positions.S,
                    Height = "6-0",
                    Weight = 206,
                    Age = 25,
                    Exp = 4,
                    College = "Central Florida",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 69
                },
                new Player
                {
                    TeamId = teamId,
                    Number = 37,
                    LastName = "Allen",
                    FirstName = "Ricardo",
                    Position = Positions.S,
                    Height = "5-9",
                    Weight = 186,
                    Age = 24,
                    Exp = 2,
                    College = "Purdue",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 65
                },

                // Free Safety
                new Player
                {
                    TeamId = teamId,
                    Number = 38,
                    LastName = "Goldson",
                    FirstName = "Dashon",
                    Position = Positions.FS,
                    Height = "6-2",
                    Weight = 200,
                    Age = 32,
                    Exp = 9,
                    College = "Washington",
                    Speed = 85,
                    Strength = 70,
                    Agility = 88,
                    Awareness = 80,
                    Fragility = 20,
                    Morale = 85,
                    Passing = 15,
                    Catching = 60,
                    Rushing = 25,
                    Blocking = 30,
                    Tackling = 85,
                    Coverage = 90,
                    Kicking = 10,
                    Potential = 85,
                    Progression = 75,
                    Health = 92,
                    Discipline = 76
                }
            };

            db.Players.AddRange(players);
            await db.SaveChangesAsync();
            Console.WriteLine($"  ✓ Added {players.Length} DBs (CB/S/FS)");
        }
    }
}
