@startuml
title Gridiron Simulation System - StateLibrary - Components
caption 25+ skills checks for realistic gameplay
package StateLibrary {
  component "BigRunSkillsCheck" <<C# Class>> as 96
  component "BlockingSuccessSkillsCheck" <<C# Class>> as 94
  component "FairCatchOccurredSkillsCheck" <<C# Class>> as 104
  component "FieldGoal (Play)" <<C# Class>> as 85
  component "FieldGoalBlockOccurredSkillsCheck" <<C# Class>> as 101
  component "FieldGoalMakeOccurredSkillsCheck" <<C# Class>> as 100
  component "FumbleOccurredSkillsCheck" <<C# Class>> as 97
  component "FumbleRecoverySkillsCheckResult" <<C# Class>> as 98
  component "InterceptionOccurredSkillsCheck" <<C# Class>> as 93
  component "Kickoff (Play)" <<C# Class>> as 83
  component "MuffedCatchOccurredSkillsCheck" <<C# Class>> as 105
  component "Pass (Play)" <<C# Class>> as 82
  component "PassCompletionSkillsCheck" <<C# Class>> as 91
  component "PassProtectionSkillsCheck" <<C# Class>> as 92
  component "Punt (Play)" <<C# Class>> as 84
  component "PuntBlockOccurredSkillsCheck" <<C# Class>> as 103
  component "PuntDistanceSkillsCheckResult" <<C# Class>> as 102
  component "Run (Play)" <<C# Class>> as 81
  component "TackleBreakSkillsCheck" <<C# Class>> as 95
  component "YardsAfterCatchSkillsCheck" <<C# Class>> as 99
}
85 ..> 101 : Checks blocks
85 ..> 100 : Checks make/miss
83 ..> 104 : Checks fair catch
83 ..> 97 : Checks fumbles
82 ..> 97 : Checks fumbles
82 ..> 93 : Checks interceptions
82 ..> 91 : Checks completion
82 ..> 92 : Checks sacks
82 ..> 99 : Calculates YAC
84 ..> 104 : Checks fair catch
84 ..> 97 : Checks fumbles
84 ..> 105 : Checks muffs
84 ..> 103 : Checks blocks
84 ..> 102 : Calculates distance
81 ..> 96 : Checks breakaway
81 ..> 94 : Checks blocking
81 ..> 97 : Checks fumbles
81 ..> 95 : Checks tackle breaks
@enduml

